In [1]:
import webbrowser
thelink="https://zhuanlan.zhihu.com/p/31064202"
webbrowser.open(thelink)

True

In [2]:
import pandas as pd

In [3]:
df=pd.read_clipboard()

In [4]:
df=pd.read_csv('C:\\Users\\wenca\\Desktop\\Original desk\\xgboost\\csv_demo\\1.csv')

In [6]:
df.dropna()

Empty DataFrame
Columns: [month, stock, status, return, EP, EPcut, BP, SP, NCFP, OCFP, DP, G/PE, Sales_G_q, Profit_G_q, OCF_G_q, ROE_G_q, ROE_q, ROE_ttm, ROA_q, ROA_ttm, grossprofitmargin_q, grossprofitmargin_ttm, profitmargin_q, profitmargin_ttm, assetturnover_q, assetturnover_ttm, operationcashflowratio_q, operationcashflowratio_ttm, financial_leverage, debtequityratio, cashratio, currentratio, ln_capital, HAlpha, return_1m, return_3m, return_6m, return_12m, wgt_return_1m, wgt_return_3m, wgt_return_6m, wgt_return_12m, exp_wgt_return_1m, exp_wgt_return_3m, exp_wgt_return_6m, exp_wgt_return_12m, std_FF3factor_1m, std_FF3factor_3m, std_FF3factor_6m, std_FF3factor_12m, std_1m, std_3m, std_6m, std_12m, ln_price, beta, turn_1m, turn_3m, turn_6m, turn_12m, bias_turn_1m, bias_turn_3m, bias_turn_6m, bias_turn_12m, rating_average, rating_change, rating_targetprice, holder_avgpctchange, macd, dea, dif, rsi, psy, bias]
Index: []

[0 rows x 74 columns]

In [9]:
type(df)

pandas.core.frame.DataFrame

In [18]:
df1=pd.DataFrame(df,columns=['month','stock','status','return','EP'])

In [21]:
s=df1['stock']

In [23]:
pd.Series(s,index=[a,b,c])

NameError: name 'a' is not defined

In [25]:
df2=pd.DataFrame(df,columns=['aa','month','stock','status','return','EP'])

In [27]:
df2['aa']=range(0,len(df2))

df2

In [29]:
df2['aa']=pd.Series(df1.stock)

In [34]:
df2.to_html('df2.html')

In [35]:
df2.to_json('df2.json')

In [36]:
df2.shape

(3541, 6)

In [37]:
df2.head(3)

aa  month      stock  status  return            EP
0  000001.SZ      1  000001.SZ       1     NaN -2.990000e-13
1  000002.SZ      1  000002.SZ       1     NaN  5.560310e-01
2  000003.SZ      1  000003.SZ       1     NaN -4.599060e-01

In [38]:
df.tail(5)

month      stock  status  return  EP  EPcut  BP  SP  NCFP  OCFP  ...   \
3536      1  603809.SH       0     NaN NaN    NaN NaN NaN   NaN   NaN  ...    
3537      1  603848.SH       0     NaN NaN    NaN NaN NaN   NaN   NaN  ...    
3538      1  603856.SH       0     NaN NaN    NaN NaN NaN   NaN   NaN  ...    
3539      1  603916.SH       0     NaN NaN    NaN NaN NaN   NaN   NaN  ...    
3540      1  603970.SH       0     NaN NaN    NaN NaN NaN   NaN   NaN  ...    

      rating_average  rating_change  rating_targetprice  holder_avgpctchange  \
3536             NaN            NaN                 NaN                  NaN   
3537             NaN            NaN                 NaN                  NaN   
3538             NaN            NaN                 NaN                  NaN   
3539             NaN            NaN                 NaN                  NaN   
3540             NaN            NaN                 NaN                  NaN   

      macd  dea  dif  rsi  psy  bias  
3536   NaN  NaN  NaN  NaN  NaN   NaN  
3537   NaN  NaN  NaN  NaN  NaN   NaN  
3538   NaN  NaN  NaN  NaN  NaN   NaN  
3539   NaN  NaN  NaN  NaN  NaN   NaN  
3540   NaN  NaN  NaN  NaN  NaN   NaN  

[5 rows x 74 columns]

In [49]:
df3=df2[['month','stock','EP']][11:21]
df3

month      stock        EP
11      1  000012.SZ  0.057316
12      1  000013.SZ       NaN
13      1  000014.SZ -1.229290
14      1  000015.SZ -2.176820
15      1  000016.SZ  1.011090
16      1  000017.SZ -2.740670
17      1  000018.SZ -2.525470
18      1  000019.SZ -0.304300
19      1  000020.SZ -2.428240
20      1  000021.SZ -0.833429

In [67]:
df4=df3.loc[0:10,'month':'EP']

df4

In [68]:
df4

Empty DataFrame
Columns: [month, stock, EP]
Index: []

In [70]:
df5=df3.dropna()

df5

In [73]:
df6=df3.dropna(axis=1)

In [75]:
df7=df3.dropna(axis=1,how='all')

In [77]:
df7=df3.dropna(axis=1,thresh=2)

In [79]:
df8=df3.fillna(value=11)

In [80]:
df8

month      stock         EP
11      1  000012.SZ   0.057316
12      1  000013.SZ  11.000000
13      1  000014.SZ  -1.229290
14      1  000015.SZ  -2.176820
15      1  000016.SZ   1.011090
16      1  000017.SZ  -2.740670
17      1  000018.SZ  -2.525470
18      1  000019.SZ  -0.304300
19      1  000020.SZ  -2.428240
20      1  000021.SZ  -0.833429

In [87]:
import numpy as np
import numpy.linalg
x = np.array([[1,2],[3,4],[5,6]])


In [2]:
bin(int('11',2)+int('1',2))

'0b100'

In [89]:
x[0:1,1:2]

array([[2]])

In [90]:
np.linalg

<module 'numpy.linalg' from 'C:\\Users\\wenca\\APP\\Anaconda\\lib\\site-packages\\numpy\\linalg\\__init__.py'>

In [11]:
nums1=[1,5,2]
nums2=[9,7]
nums3=nums1+nums2

In [12]:
nums3.sort()

In [13]:
nums3

[1, 2, 5, 7, 9]

TypeError: integer argument expected, got float

In [4]:
a='257'

In [9]:
Hex=hex(int(a))[2:]

In [10]:
Hex

'101'

In [18]:
from collections import Counter
s="bbscss"
a=[]
for i in s:
    a.append(i)
bea = Counter(a).most_common(len(Counter(a)))

[('s', 3), ('b', 2), ('c', 1)]

In [33]:
import numpy as np
x=np.array(range(3.0))
x[0]=1.1122

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
import pandas as pd
a=pd.DataFrame(cols=[1,2,3])

TypeError: __init__() got an unexpected keyword argument 'cols'

In [46]:
data = np.array([np.arange(10)]*3).T
data1=[np.arange(10)]*3
data1

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [14]:
b=a

In [15]:
a[0]=11

In [16]:
b

array([11,  1,  2])

In [17]:
a=np.array([1,2.332,3])
b=a


In [18]:
a

array([1.   , 2.332, 3.   ])

In [19]:
a[0]=2.33333333

In [21]:
a=np.array(range(5))

In [22]:
a[0]=5.4321

In [29]:
b=np.arange(5.0)

In [30]:
b[0]=1.22222

In [31]:
b[1]=0.9887

In [32]:
b

array([1.22222, 0.9887 , 2.     , 3.     , 4.     ])